version: "3.7"
services:
  app:
    build:
      args:
        user: Shawon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crm
    container_name: crm-application
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - database
    links:
      - database
    networks:
      - crm-network
  nginx:
    image: nginx:alpine
    container_name: crm-nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - crm-network
    depends_on:
      - database
      - phpmyadmin
  database:
    image: mysql:5.7
    container_name: crm-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - crm-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - 9004:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
